### PR TITLE
fix: keep line breaks and hide overflow in info box

### LINKED ISSUE #37: Autocompletion for context example data overflows the UI
### Describe the Bug

The autocompletion content for context example data overflows the UI, see screenshot

### Steps to Reproduce

1. Add a context with a subcontext as example data 

E.g. 
```
{
    "parsedInvoice":  {
        "invoiceUrl": "https://www.myDMS.com/documents/5983371298572",
        "firstName": "Peter",
        "lastName": "Miller",
        "department": "Sales",
        "billerName": "ACME Corp",
        "billerStreet": "Acme Avenue",
        "billerStreetNo": 1,
        "billerZip": "11111",
        "billerCity": "Acme City",
        "item": "Some product",
        "invoiceValue": 5000,
        "invoiceDate": "2022-12-12",
        "purpose": "Very important for our team"
    }
}
```

3. Use autocompletion in another task for this context
4. Since it auto-removes white spaces and does only break on white spaces, it overflows

Bildschirmfoto 2023-04-17 um 18 14 06

### Expected Behavior
- Properly format whitespaces in contexts/jsons
- Wrap even if no white spaces

### Environment

- Recent Web Modeler as of April 17th 2023

### PR DESCRIPTION
**Pull request by marstamm**
closes #37
image

### CODE REVIEW

File: src/theme/theme.js [hunk 1]
```diff
@@ -12,6 +12,16 @@ export const baseTheme = EditorView.theme({
   '&.cm-editor.cm-focused': {
     outline: 'none',
   },
+  '& .cm-completionInfo': {
```
Comment (nikku) [inline src/theme/theme.js:15]: As indicated in the weekly: Is there a chance for us to provide examples as _verbatim_ (monospace)? I think that would benefit the eye.

If not, then this looks just as we need it!

**Review by nikku — COMMENTED** [review]
Good to merge from my end.

File: src/theme/theme.js (hunk 1 above)
Comment (marstamm) [reply src/theme/theme.js:15]: I would handle mono-space in the example extractor. In the feel-editor, this would affect all variable info and I don't think we want this

Comment (nikku) [reply src/theme/theme.js:15]: :+1: 

I'm not 100% sure how we can best support that. You're the expert.

At some point we'd want to improve our previews anyway. We could event consider to not act until that date.

Comment (marstamm) [reply src/theme/theme.js:15]: > I'm not 100% sure how we can best support that. You're the expert.

Codemirror supports passing DOM elements. I did not have a deeper look, so this might blow up when we merge multiple elements currently, but thats the direction I would want to go

Comment (nikku) [reply src/theme/theme.js:15]: :+1:
